### ISSUE TITLE
Remove DataFrames.jl 

### ISSUE THREAD

**Issue by odow** [EPOC-NZ/JADE.jl#12]
Only usage is 

https://github.com/EPOC-NZ/JADE.jl/blob/b705880bfb472cb433c385b95d23f782404ded07/src/time.jl#L117-L129

and that method is never called.

See also https://github.com/EPOC-NZ/JADE.jl/issues/8

**Comment by adow031** [comment]
Currently the reading of data files is quite brittle. Should dataframes.jl be used to improve this?

**Comment by odow** [comment]
> Currently the reading of data files is quite brittle. Should dataframes.jl be used to improve this?

Potentially. My first goal is to strip out everything that isn't being used. We can re-add dataframes later if there are problems with the reading.

**Comment by odow** [comment]
Closed by #15
