### ISSUE TITLE
The deal with WrapHistorical

### ISSUE THREAD

**Issue by odow** [EPOC-NZ/JADE.jl#19]
I think `WrapHistorical` is just:

  * https://github.com/odow/SDDP.jl/issues/414
  * https://github.com/odow/SDDP.jl/pull/420

**Comment by adow031** [comment]
I think that the reason I kept using `WrapHistorical` was so that I could create a custom `sample_scenario` function that would set `terminated_due_to_cycle = true`.

https://github.com/EPOC-NZ/JADE.jl/blob/b705880bfb472cb433c385b95d23f782404ded07/src/sddp_modifications.jl#L265-L291

**Comment by odow** [comment]
We could add that as an option. Or at the very least, simplify this implementation.

**Comment by odow** [comment]
Closed by #27
