### ISSUE TITLE
Use of private SDDP function

### ISSUE THREAD

**Issue by odow** [EPOC-NZ/JADE.jl#39]
Just found this one:
https://github.com/EPOC-NZ/JADE.jl/blob/79b364d8ce6eb64c5d615e970bf881105e85b703/src/simulate.jl#L94

It looks like it's the only instance left in `develop`.

**Comment by adow031** [comment]
The use of this function wasn't necessary, but meant that I didn't have to duplicate the code (conditioned on whether the user specified an initial state) for each `SDDP.simulate` call.

**Comment by odow** [comment]
Fixed in https://github.com/EPOC-NZ/JADE.jl/pull/38/commits/f56b433bc2caf644c20fde7f9fe63948937beffe. I guess fields are fair game, but I can see myself refactoring `_` methods without thinking of the consequences.
