### ISSUE TITLE
Excel file

### ISSUE THREAD

**Issue by GislainUhl** [EPOC-NZ/JADE.jl#42]
Hi,
The documentation mentions an excel file "runJADE.xlsm". Where is this file available?
Regards,
Gislain

**Comment by adow031** [comment]
I had been waiting for the official JADE data sets to be released before uploading the Excel file, but it's been 9 months since JADE was released, so I've put up the xlsm file and the jl file that goes with it.

You can find these files in the latest commit: 8a6cfe252afb13388a2b2e29f3a346d056625ffb

**Comment by GislainUhl** [comment]
Thank you.
