### ISSUE TITLE
inputs for a 2023 run

### ISSUE THREAD

**Issue by GislainUhl** [EPOC-NZ/JADE.jl#43]
Hi Team,
I have started to play with the model and am trying to make a 2023 run.
How is the weekly split between peak/offpeak/shoulder defined ("hours_per_block.csv") ?
Is there a 2023 input dataset available somewhere?
Regards,
Gislain

**Comment by odow** [comment]
> Is there a 2023 input dataset available somewhere?

No. The EA is still in the process of curating the datasets for JADE:

https://www.emi.ea.govt.nz/Wholesale/Tools/JADE

**Comment by GislainUhl** [comment]
Thanks for you answer, and how is the weekly split between peak/offpeak/shoulder defined ("hours_per_block.csv") ?

**Comment by adow031** [comment]
JADE is agnostic to the input assumptions. You could use percentiles of load within a week or any other metric to determine the how a week's 336 half-hour periods are divided into a set of load blocks. Also note that the number of load blocks is not limited to 3.

**Comment by GislainUhl** [comment]
That's awesome, thank you.
